spring:
  application:
    name: lionkorea
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      show-sql: false
  h2:
    console:
      enabled: true
  jwt:
    secret: fkdldhszhfldkfmfdnlgksxhdgkqrhksfltjqltmfmfaksemsmswnddlek

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug