server:
  host: https://

spring:
  application:
    name: lionkorea
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
      show-sql: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jwt:
    secret: ${JWT_SECREATE_KEY}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true