spring:
  application:
    name: lionkorea
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
      show-sql: false
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.jljftvddfkqbvhraqgcr
    password: ywJPUFKSDpRtndVx
    driver-class-name: org.postgresql.Driver

  jwt:
    secret: fkdldhszhfldkfmfdnlgksxhdgkqrhksfltjqltmfmfaksemsmswnddlek

  data:
    redis:
      host: redis-19104.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
      port: 19104
      username: default
      password: wAgkh0VGUECkrwLvj7UByVHi2d8A3iVC
      ssl:
        enabled: true