spring:
  application:
    name: lionkorea
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jwt:
    secret: fkdldhszhfldkfmfdnlgksxhdgkqrhksfltjqltmfmfaksemsmswnddlek

  data:
      redis:
        host: redis-19104.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com
        port: 19104
        username: default
        password: wAgkh0VGUECkrwLvj7UByVHi2d8A3iVC
        ssl:
          enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

supabase:
  url: https://jljftvddfkqbvhraqgcr.supabase.co