# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}

jobs:
  build:

    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant all permissions to Gradle Wrapper
      run: chmod 777 ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build --exclude-task test

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: build/libs/*-SNAPSHOT.jar


  deploy:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Create build/libs directory
        run: mkdir -p build/libs

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: build/libs

      - name: Find JAR file
        id: jar
        run: |
          if [ ! -d build/libs ]; then
            echo "Error: build/libs directory not found."
            exit 1
          fi
          
          JAR_FILE=$(find build/libs -name "*-SNAPSHOT.jar" | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "Error: JAR file not found."
            exit 1
          fi
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Transfer JAR to Remote Server
        run: |
          echo "${{ secrets.SSH_SECRET_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          echo "Attempting to transfer $JAR_FILE"
          
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            $JAR_FILE \
            $SERVER_USERNAME@$SERVER_IP:/home/$SERVER_USERNAME/app/

      - name: Deploy Application on Remote Server
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP << EOF
            chmod +x /home/$SERVER_USERNAME/app/lionkorea-0.0.1-SNAPSHOT.jar
            PID=$(sudo netstat -tulnp | grep 8080 | awk '{print $7}' | cut -d'/' -f1)
            if [ -n "$PID" ]; then
              sudo kill -9 "$PID"
              echo "프로세스 $PID가 종료되었습니다."
              else
              echo "8080 포트를 사용하는 프로세스가 없습니다."
            fi
            nohup env \
              DB_URL="${{ secrets.DB_URL }}" \
              DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              JWT_SECREATE_KEY="${{ secrets.JWT_SECREATE_KEY }}" \
              MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}" \
              MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}" \
              REDIS_HOST="${{ secrets.REDIS_HOST }}" \
              REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}" \
              REDIS_PORT="${{ secrets.REDIS_PORT }}" \
              REDIS_USERNAME="${{ secrets.REDIS_USERNAME }}" \
              java -jar /home/$SERVER_USERNAME/app/lionkorea-0.0.1-SNAPSHOT.jar > /home/$SERVER_USERNAME/app/app.log 2>&1 &
          EOF

      - name: Clean up
        run: rm -f private_key.pem

####
#  dependency-submission:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#
#    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
#    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
#    - name: Generate and submit dependency graph
#      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
####