# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}

jobs:
  build:

    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant all permissions to Gradle Wrapper
      run: chmod 777 ./gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build --exclude-task test

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifact
        path: build/libs/*-SNAPSHOT.jar


  deploy:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Create build/libs directory
        run: mkdir -p build/libs

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: build/libs

      - name: Find JAR file
        id: jar
        run: |
          if [ ! -d build/libs ]; then
            echo "Error: build/libs directory not found."
            exit 1
          fi
          
          JAR_FILE=$(find build/libs -name "*-SNAPSHOT.jar" | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "Error: JAR file not found."
            exit 1
          fi
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Transfer JAR to Remote Server
        run: |
          echo "${{ secrets.SSH_SECRET_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          echo "Attempting to transfer $JAR_FILE"
          
          scp -i private_key.pem -o StrictHostKeyChecking=no \
            $JAR_FILE \
            $SERVER_USERNAME@$SERVER_IP:/home/$SERVER_USERNAME/app/

      - name: Deploy Application on Remote Server
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_IP << EOF
            export DB_URL="${DB_URL}"
            export DB_PASSWORD="${DB_PASSWORD}"
            export DB_USERNAME="${DB_USERNAME}"
            export JWT_SECRET_KEY="${JWT_SECRET_KEY}"
            export MAIL_PASSWORD="${MAIL_PASSWORD}"
            export MAIL_USERNAME="${MAIL_USERNAME}"
            export REDIS_HOST="${REDIS_HOST}"
            export REDIS_PASSWORD="${REDIS_PASSWORD}"
            export REDIS_PORT="${REDIS_PORT}"
            export REDIS_USERNAME="${REDIS_USERNAME}"
            chmod +x /home/$SERVER_USERNAME/app/deploy.sh
            /home/$SERVER_USERNAME/app/deploy.sh
          EOF
        env :
          DB_URL: ${{ secrets.DB_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}

      - name: Clean up
        run: rm -f private_key.pem

####
#  dependency-submission:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#
#    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
#    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
#    - name: Generate and submit dependency graph
#      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
####